# Generated by Django 4.0.4 on 2022-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ren_car_brand', models.CharField(max_length=50, verbose_name='Rent car brand')),
                ('rent_car_model', models.CharField(max_length=50, verbose_name='Rent car model')),
                ('rent_car_plate', models.CharField(max_length=50, verbose_name='Rent car plates')),
                ('date_of_booking', models.DateField(blank=True, null=True)),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('total_days', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('customer_email', models.CharField(max_length=50, verbose_name='Customer_email')),
                ('rent_status', models.BooleanField()),
            ],
        ),
    ]
