# Generated by Django 4.0.4 on 2022-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcar',
            old_name='ren_car_brand',
            new_name='rent_car_brand',
        ),
    ]
