# Generated by Django 4.0.4 on 2022-05-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Car brand')),
                ('car_model', models.CharField(max_length=50, verbose_name='Car model')),
                ('car_fuel_type', models.CharField(max_length=50, verbose_name='fuel type')),
                ('count_of_seats', models.IntegerField()),
                ('car_color', models.CharField(max_length=50, verbose_name='Car color')),
                ('car_plate', models.CharField(max_length=7, verbose_name='Car plates')),
                ('car_image1', models.ImageField(upload_to='images/car_images/')),
                ('car_image2', models.ImageField(upload_to='images/car_images/')),
                ('car_image3', models.ImageField(upload_to='images/car_images/')),
                ('car_description', models.CharField(max_length=100)),
                ('price_per_day', models.IntegerField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_type.car_type')),
            ],
        ),
    ]
