# Generated by Django 4.0.4 on 2022-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_plate',
            field=models.CharField(max_length=15, verbose_name='Car plates'),
        ),
    ]
