# Generated by Django 4.0.4 on 2022-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_car_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_brand', 'car_model', 'car_plate']},
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
