# Generated by Django 4.0.4 on 2022-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_fname', models.CharField(max_length=30, verbose_name='First name')),
                ('owner_lname', models.CharField(max_length=30, verbose_name='Last name')),
                ('owner_db', models.DateField()),
                ('owner_gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=10, verbose_name='gender')),
                ('owner_address', models.CharField(max_length=50, verbose_name='Address')),
                ('owner_email', models.CharField(max_length=40, unique=True, verbose_name='email')),
                ('owner_password', models.CharField(max_length=30, unique=True, verbose_name='email password')),
                ('owner_number', models.CharField(max_length=20, unique=True, verbose_name='Telephone_number')),
                ('owner_city', models.CharField(max_length=20, verbose_name='City')),
                ('owner_drive_license', models.ImageField(upload_to='img/Owner_License/')),
                ('isOwner', models.BooleanField(default=True)),
            ],
        ),
    ]
