# Generated by Django 4.0.4 on 2022-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_drive_license',
            field=models.ImageField(null=True, upload_to='images/Owner_License/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_gender',
            field=models.CharField(max_length=10, verbose_name='gender'),
        ),
    ]
